#!/bin/bash

# 获取当前工作目录
work_dir=$(git rev-parse --show-toplevel)
echo "工作目录: $work_dir"

# 标志文件路径 
flag_file="$work_dir/.pre-push-flag"
echo "标志文件路径: $flag_file"

# 获取当前分支名称9
current_branch=$(git rev-parse --abbrev-ref HEAD)
echo "当前分支: $current_branch"

# 如果当前分支是 develop
if [ "$current_branch" = "develop" ]; then
    echo "当前分支是 develop。切换到 main 分支..."
  
    git checkout main
    #git pull origin main

    echo "获取 develop 分支最后一次提交信息...  "
    last_commit_msg=$(git log develop -1 --pretty=%B)

    echo "合并 develop 分支，使用 --squash 选项...  "
    git merge --squash develop

    echo "提交更改... "
    git commit -m "$last_commit_msg"

    echo "合并到 main 成功完成 "

# 如果当前分支是 main
elif [ "$current_branch" = "main" ]; then
        # 创建标志文件
    touch "$flag_file"
    
    
    echo "切换到 develop 分支并合并 main...  "
    git checkout develop 
    git merge -X theirs main
    if [ $? -ne 0 ]; then
        echo "切换到 develop 分支并合并 main 失败，推送已中止  "
        exit 1
    fi
    echo "切换到 develop 分支并合并 main 成功完成  "

        # 删除标志文件
    rm "$flag_file"
fi

# 继续执行推送
exit 0