#!/bin/bash

# 获取当前工作目录
work_dir=$(git rev-parse --show-toplevel)
echo "工作目录: $work_dir"

# 标志文件路径
flag_file="$work_dir/.pre-commit-flag"
echo "标志文件路径: $flag_file"

# 获取当前分支名称
current_branch=$(git rev-parse --abbrev-ref HEAD)
echo "当前分支: $current_branch"

# 如果当前分支是 develop
if [ "$current_branch" = "develop" ]; then
    # 检查标志文件是否存在，防止重复操作
    if [ -f "$flag_file" ]; then
        echo "标志文件存在，跳过版本号更新和合并操作"
        # 删除标志文件，确保下次提交时不受影响
        rm "$flag_file"
        echo "标志文件已删除，准备进行下一次提交操作"
    else
        # 创建标志文件，表示已处理
        touch "$flag_file"
        echo "Flag file created: $flag_file"
        # 在提交之前执行构建命令
        echo "Running npm run build before committing..."
        npm run build

        # 如果构建失败，终止提交
        if [ $? -ne 0 ]; then
            echo "Build failed, aborting commit."
            exit 1
        fi

        # 获取 develop 分支的最后一次提交信息
        last_commit_msg=$(git log develop -1 --pretty=%B)
        echo "Last commit message: $last_commit_msg"

        # 将 out 目录添加到 Git
        git add out/
        echo "Adding out directory to git..."

        # 提交 out 目录
        # 在提交时使用原有的提交信息，以避免影响历史记录
        git commit --amend --no-edit --message "$last_commit_msg" 
        echo "Out directory committed with the last commit message."

        
        
        # 如果提交成功，提示用户继续提交其他更改
        echo "Out directory committed, proceed with other changes if needed."
    fi

# 如果当前分支是 main
elif [ "$current_branch" = "main" ]; then
    echo "当前分支是 main，不需要操作。"
fi

# 继续执行提交
exit 0